### ISSUE TITLE
Unable to launch in https using h2o locally

### ISSUE THREAD

**Issue by reznord** [kristoferbaxter/preact-hn#15]
Hi @kristoferbaxter, a huge thanks for this repo.

So, I am trying to set this up in my local machine with the instructions provided by you in the [`README.md`](https://github.com/kristoferbaxter/preact-hn#installation).

Here is how I have created a self signed certificates:
<img width="776" alt="screen shot 2017-06-21 at 6 41 12 pm" src="https://user-images.githubusercontent.com/3415488/27385739-45379bd8-56b1-11e7-89e8-59023e6f2355.png">

When I start the project locally using the following command `yarn run bundle:prod; yarn run start`, I am getting the following log:
https://pastebin.mozilla.org/9025466

And this is what I get in the console:
<img width="1280" alt="screen shot 2017-06-21 at 6 46 28 pm" src="https://user-images.githubusercontent.com/3415488/27386043-29e2cb04-56b2-11e7-90b8-694246c2f7f1.png">

Can you help me where I am going wrong?

**Comment by reznord** [comment]
But I am able to launch the application using `http`

Screenshot Link - https://cl.ly/0u3L0E3U2p28

**Comment by kristoferbaxter** [comment]
Updated readme – looks like this somehow got out of date.

If you access https://localhost:5443 do things work as expected?

**Comment by reznord** [comment]
Nope, that is not working. Still the same blank screen.

<img width="1280" alt="screen shot 2017-06-21 at 10 27 19 pm" src="https://user-images.githubusercontent.com/3415488/27396549-f5bb12b8-56d0-11e7-8709-e598b3f712f6.png">

**Comment by kristoferbaxter** [comment]
Would it be possible for you to paste the terminal contents when you run `yarn run start`?

**Comment by reznord** [comment]
sure, this is what I get when I run `yarn run start`:

```
➜  preact-hn git:(master) yarn run start
yarn run v0.24.6
$ node_modules/.bin/nodemon -e js,css --config nodemon.config.json --exec 'yarn' start:node:dev-after-bundle
[nodemon] 1.11.0
[nodemon] reading config /Users/Anup/Projects/pwa/preact-hn/nodemon.config.json
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: /Users/Anup/Projects/pwa/preact-hn/.git/**/* .nyc_output .sass-cache bower_components coverage /Users/Anup/Projects/pwa/preact-hn/node_modules/**/*
[nodemon] watching: /Users/Anup/Projects/pwa/preact-hn/src/**/*
[nodemon] watching extensions: js,css
[nodemon] bind start -> `yarn run start:h2o`
[nodemon] bind restart -> `osascript -e 'display notification "hn-web restarting" with title "nodemon"'`
[nodemon] starting `yarn start:node:dev-after-bundle`
[nodemon] child pid: 15427
[nodemon] watching 48 files
yarn run v0.24.6
yarn start:node:dev-after-bundle v0.24.6
$ cd dist/server && h2o -c h2o.config.yaml
$ yarn run bundle:dev; yarn run start:node
yarn run v0.24.6
$ BUNDLE_ENV=dev yarn run bundle:chrome; yarn run bundle:server
yarn run v0.24.6
$ BABEL_ENV=build.chrome node_modules/.bin/webpack --config config/webpack.chrome.js --json > dist/chrome/webpack.json
(node:15437) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
✨  Done in 5.29s.
yarn run v0.24.6
$ BABEL_ENV=build.server node_modules/.bin/webpack --config config/webpack.server.js --json > dist/server/webpack.json
(node:15444) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
✨  Done in 2.48s.
✨  Done in 8.24s.
yarn run v0.24.6
$ node dist/server/restify.server.js | ./node_modules/.bin/bunyan
hn-web listening at http://[::]:22164
[2017-06-21T17:09:59.460Z]  INFO: hn-web/15450 on Anups-MacBook-Pro.local: RESOURCES – Load – chrome success
[2017-06-21T17:09:59.461Z]  INFO: hn-web/15450 on Anups-MacBook-Pro.local: RESOURCES – Load – firefox success
[2017-06-21T17:09:59.461Z]  INFO: hn-web/15450 on Anups-MacBook-Pro.local: RESOURCES – Load – safari success
[2017-06-21T17:09:59.461Z]  INFO: hn-web/15450 on Anups-MacBook-Pro.local: RESOURCES – Load – edge success
[2017-06-21T17:09:59.462Z]  INFO: hn-web/15450 on Anups-MacBook-Pro.local: RESOURCES – Load – fallback success

```

**Comment by kristoferbaxter** [comment]
I upgraded to the latest version of h2o and couldn't reproduce this issue.

Also, tried a fresh install on a new machine and no luck!

Only followup I have right now is did you allow h2o to accept connections? (See https://www.google.com/search?biw=1732&bih=1428&tbm=isch&sa=1&q=allow+accept+connections+mac&oq=allow+accept+connections+mac&gs_l=psy-ab.3...6903.6903.0.7467.1.1.0.0.0.0.48.48.1.1.0....0...1.1.64.psy-ab..0.0.0.SgtGNbTxcfY#imgrc=_)

**Comment by Michael-Reich** [comment]
I have the same problem:

This shows up:
```

[h2o.config.yaml:15] in command listen, failed to load private key file:key.pem:No such file or directory

error Command failed with exit code 78.
```

**Comment by kristoferbaxter** [comment]
Hi @Michael-Reich, thanks for the report.

Could you try adding a self-signed cert to the proxy folder?

![screen shot 2017-09-15 at 3 53 31 pm](https://user-images.githubusercontent.com/61764/30506109-0f137660-9a2e-11e7-81c7-9260b1cd596d.png)

**Comment by Michael-Reich** [comment]
Yeah did that already just took time to recognize it. Works now!

Do you think about adding a login? I would be very interested to use this in a semi-real project. :)

**Comment by kristoferbaxter** [comment]
This example is meant more as an inspiration of how one could build a HN clone using Preact and a ton of opinions.

If you're looking for something closer to a real project using Preact, I highly recommend https://github.com/developit/preact-cli
