### ISSUE TITLE
tsickle

### ISSUE THREAD

**Issue by stereobooster** [kristoferbaxter/preact-hn#33]
Just wondering if https://github.com/angular/tsickle can improve minification. Have you tried it?

**Comment by kristoferbaxter** [comment]
Perhaps it would improve minification. 

Tsickle + Advanced Compilation would net a lower ES5 bundle size for sure, but I don't have conclusive data comparing ES20XX + UglifyES/Babel-Minify versus ES20XX -> ES5 + Closure Compiler Advanced.

There is a sample repo here where some exploration around combining Tsickle + Webpack + Closure Compiler was done: https://github.com/kristoferbaxter/closure-compiler-typescript-test

**Comment by stereobooster** [comment]
Thank you. I just was wondering if you considered to use it or not. I see you took everything into consideration
