### ISSUE TITLE
ES modules for the browser?

### ISSUE THREAD

**Issue by stereobooster** [kristoferbaxter/preact-hn#34]
Any plans to update this repo to support ES modules? https://github.com/kristoferbaxter/preset-env-modules/blob/master/.babelrc.js

And terser as minifier I guess.

**Comment by kristoferbaxter** [comment]
Haven't decided yet. This project goes a bit further than what's possible with module/no-module output as it targets output with more granularity.

Perhaps a sibling implementation would be prudent.

**Comment by stereobooster** [comment]
This is what I thought about https://dev.to/stereobooster/my-wishlist-for-javascript-transpiler-3080, see "Wish 1: painless polyfills" and https://github.com/Rich-Harris/shimport. (issue can be closed)
